### ISSUE TITLE
Plugin cannot load commands on velocity server

### ISSUE THREAD

**Issue by xNovyz** [mehmet-27/PunishManager#27]
Version 1.4.4

[latest.log](https://github.com/mehmet-27/PunishManager/files/10105065/latest.log)

**Comment by mehmet-27** [comment]
Can you update to the latest version and try again. and what language file do you use by default

**Comment by mehmet-27** [comment]
You probably have missing values ​​in your default language file.

**Comment by mehmet-27** [comment]
Can you try again by setting en_US

**Comment by xNovyz** [comment]
Im using the 1.4.4 and the default settings

**Comment by mehmet-27** [comment]
Very weird i will check for you

**Comment by mehmet-27** [comment]
The cause of the problem is `commandNames` at: https://github.com/mehmet-27/PunishManager/blob/4d10aa6c9c9f576b7572fce2716805875c11559e/velocity/src/main/java/com/mehmet_27/punishManager/velocity/punishmanager.
but it says commandReplacements in the config files. I'm releasing a new update. By downloading the latest version, you can use it without any problems.
